import { NextResponse } from 'next/server';

export const BOOKS = [
  // Perjanjian Lama
  { code: 'GEN', name: 'Kejadian' },
  { code: 'EXO', name: 'Keluaran' },
  { code: 'LEV', name: 'Imamat' },
  { code: 'NUM', name: 'Bilangan' },
  { code: 'DEU', name: 'Ulangan' },
  { code: 'JOS', name: 'Yosua' },
  { code: 'JDG', name: 'Hakim-hakim' },
  { code: 'RUT', name: 'Rut' },
  { code: '1SA', name: '1 Samuel' },
  { code: '2SA', name: '2 Samuel' },
  { code: '1KI', name: '1 Raja-raja' },
  { code: '2KI', name: '2 Raja-raja' },
  { code: '1CH', name: '1 Tawarikh' },
  { code: '2CH', name: '2 Tawarikh' },
  { code: 'EZR', name: 'Ezra' },
  { code: 'NEH', name: 'Nehemia' },
  { code: 'EST', name: 'Ester' },
  { code: 'JOB', name: 'Ayub' },
  { code: 'PSA', name: 'Mazmur' },
  { code: 'PRO', name: 'Amsal' },
  { code: 'ECC', name: 'Pengkhotbah' },
  { code: 'SNG', name: 'Kidung Agung' },
  { code: 'ISA', name: 'Yesaya' },
  { code: 'JER', name: 'Yeremia' },
  { code: 'LAM', name: 'Ratapan' },
  { code: 'EZK', name: 'Yehezkiel' },
  { code: 'DAN', name: 'Daniel' },
  { code: 'HOS', name: 'Hosea' },
  { code: 'JOL', name: 'Yoel' },
  { code: 'AMO', name: 'Amos' },
  { code: 'OBA', name: 'Obaja' },
  { code: 'JON', name: 'Yunus' },
  { code: 'MIC', name: 'Mikha' },
  { code: 'NAM', name: 'Nahum' },
  { code: 'HAB', name: 'Habakuk' },
  { code: 'ZEP', name: 'Zefanya' },
  { code: 'HAG', name: 'Hagai' },
  { code: 'ZEC', name: 'Zakharia' },
  { code: 'MAL', name: 'Maleakhi' },
  // Perjanjian Baru
  { code: 'MAT', name: 'Matius' },
  { code: 'MRK', name: 'Markus' },
  { code: 'LUK', name: 'Lukas' },
  { code: 'JHN', name: 'Yohanes' },
  { code: 'ACT', name: 'Kisah Para Rasul' },
  { code: 'ROM', name: 'Roma' },
  { code: '1CO', name: '1 Korintus' },
  { code: '2CO', name: '2 Korintus' },
  { code: 'GAL', name: 'Galatia' },
  { code: 'EPH', name: 'Efesus' },
  { code: 'PHP', name: 'Filipi' },
  { code: 'COL', name: 'Kolose' },
  { code: '1TH', name: '1 Tesalonika' },
  { code: '2TH', name: '2 Tesalonika' },
  { code: '1TI', name: '1 Timotius' },
  { code: '2TI', name: '2 Timotius' },
  { code: 'TIT', name: 'Titus' },
  { code: 'PHM', name: 'Filemon' },
  { code: 'HEB', name: 'Ibrani' },
  { code: 'JAS', name: 'Yakobus' },
  { code: '1PE', name: '1 Petrus' },
  { code: '2PE', name: '2 Petrus' },
  { code: '1JN', name: '1 Yohanes' },
  { code: '2JN', name: '2 Yohanes' },
  { code: '3JN', name: '3 Yohanes' },
  { code: 'JUD', name: 'Yudas' },
  { code: 'REV', name: 'Wahyu' },
];

export async function GET() {
  return NextResponse.json(BOOKS);
}
